baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Gowra Streaming"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      autoHeadingID = true
      smartypants = true

